---
jenkins_url: https://newci-sandbox.office.ableton.com/

pull_requests:
  - main

pushes:
  - nre/main/test-on-sandbox
  - main

notifications:
  - name: Build failures on the main branch
    branch: main
    slack:
      - GJUMRCZKQ
