---
- name: Ensure ccache configuration directory exists
  become: true
  ansible.builtin.file:
    path: "~{{ ccache_user }}/.ccache"
    state: directory
    owner: "{{ ccache_user }}"
    group: "{{ ccache_group }}"
    mode: "0755"

- name: Initialize ccache_conf_file fact
  ansible.builtin.set_fact:
    ccache_conf_file_contents: ""

- name: Build ccache configuration file contents
  ansible.builtin.set_fact:
    ccache_conf_file_contents: >
      {{ ccache_conf_file_contents }}
      {{ item.key }} = {{ item.value }}
  loop: "{{ ccache_config_options | dict2items }}"

- name: Create ccache configuration file
  become: true
  ansible.builtin.copy:
    content: "{{ ccache_conf_file_contents }}"
    dest: "~{{ ccache_user }}/.ccache/ccache.conf"
    owner: "{{ ccache_user }}"
    group: "{{ ccache_group }}"
    mode: "0644"
