---
- name: Ensure ccache configuration directory exists
  become: true
  ansible.builtin.file:
    path: "~{{ ccache_user }}/.ccache"
    state: directory
    owner: "{{ ccache_user }}"
    group: "{{ ccache_group }}"
    mode: "0755"

- name: Create ccache configuration file
  become: true
  ansible.builtin.copy:
    content: |
      {% for key, value in ccache_config_options.items() -%}
      {{ key }} = {{ value }}
      {% endfor %}
    dest: "~{{ ccache_user }}/.ccache/ccache.conf"
    owner: "{{ ccache_user }}"
    group: "{{ ccache_group }}"
    mode: "0644"
  when: ccache_config_options | length > 0
