---
- name: Ensure ccache cache directory exists
  become: true
  file:
    path: "{{ ccache_cache_dir }}"
    state: directory
    owner: "{{ ccache_user }}"
    mode: "0755"

- name: Ensure ccache configuration directory exists
  become: true
  file:
    path: "~{{ ccache_user }}/.ccache"
    state: directory
    owner: "{{ ccache_user }}"
    mode: "0755"

- name: Initialize ccache_conf_file fact
  set_fact:
    ccache_conf_file_contents: ""

- name: Build ccache configuration file contents
  set_fact:
    ccache_conf_file_contents: >
      {{ ccache_conf_file_contents }}
      {{ item.key }} = {{ item.value }}
  with_dict: "{{ ccache_config_options }}"

- name: Create ccache configuration file
  become: true
  copy:
    content: "{{ ccache_conf_file_contents }}"
    dest: "~{{ ccache_user }}/.ccache/ccache.conf"
    owner: "{{ ccache_user }}"
    mode: "0644"
