---
- name: Ensure symlink directory exists
  become: true
  ansible.builtin.file:
    path: "{{ ccache_symlink_path }}"
    state: directory
    mode: "0755"
  when: ccache_symlink_path != ""

- name: Symlink common compiler names
  become: true
  ansible.builtin.file:
    path: "{{ ccache_symlink_path }}/{{ item }}"
    src: "{{ ccache_install_prefix }}/bin/ccache"
    state: link
    mode: "0755"
  loop: "{{ ccache_symlink_compilers }}"
  when: ccache_symlink_path != ""
