---
- name: Initialize homebrew_install_options fact
  ansible.builtin.set_fact:
    homebrew_install_options: ""

- name: Set homebrew install options
  ansible.builtin.set_fact:
    # Ansible will add the "--" to these options for us
    homebrew_install_options:
      - "build-from-source"
  when: ansible_distribution_version is version_compare('10.14', '<')

# This package must be manually installed for macOS <10.14, or else brew will attempt to
# install it from a bottle and inevitably fail.
- name: Install ccache dependencies
  community.general.homebrew:
    name: "zstd"
    install_options: "{{ homebrew_install_options }}"
    state: present
  when: ansible_distribution_version is version_compare('10.14', '<')

- name: Install ccache from homebrew
  community.general.homebrew:
    name: ccache
    install_options: "{{ homebrew_install_options }}"
    state: present
