---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-ccache-install-package-jammy
    image: ubuntu:22.04
  - name: ansible-role-ccache-install-package-noble
    image: ubuntu:24.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
